accommodation/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('room/', include('room.urls')),
    path('hostel/', include('hostel.urls')),
    path('department/', include('department.urls')),
    path('course/', include('course.urls')),
    path('allocate/', include('allocate.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from  django.urls import path
from . import views



urlpatterns=[
    path('login/',views.login,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.logout,name='logout'),
    path('profile',views.profile,name='profile'),
    path('reset',views.reset,name='reset')
]

allocate/urls.py
from django.urls import path
from .views import *


app_name='allocate'
urlpatterns=[
    path('',Index.as_view(),name='index'),
    path('update/<int:id>',Update.as_view(),name='update'),
    path('<int:id>',delete_allocate,name='delete'),
    path('approve/<int:id>',approve_allocate,name='approve'),
    path('undo_approve_allocate/<int:id>',undo_approve_allocate,name='undo_approve'),
]

course/urls.py
from django.urls import path
from .views import *


app_name='course'


urlpatterns=[
    path('',Index.as_view(),name='index'),
    path('update/<int:id>',Update.as_view(),name='update'),
    path('<int:id>',delete_course,name='delete'),
]

home/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('',Home.as_view(),name='home'),
    path('',Admin.as_view(),name='admin_dashboard'),
]

hostel/urls.py
from django.urls import path
from .views import *


app_name='hostel'


urlpatterns=[
    path('',Index.as_view(),name='index'),
    path('update/<int:id>',Update.as_view(),name='update'),
    path('<int:id>',delete_hostel,name='delete'),
]

room/urls.py
from django.urls import path
from .views import *


app_name='room'


urlpatterns=[
    path('',Index.as_view(),name='index'),
    path('update/<int:id>/',Update.as_view(),name='update'),
    path('<int:id>/',delete_room,name='delete'),
    path('apply/<int:id>/',ApplyRoom.as_view(),name='apply'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS_CHOICES=[
    ('male','MALE'),
    ('female','FEMALE'),
]
# Create your models here.
class Profile(models.Model):
     user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
     status=models.CharField(max_length=10,choices=STATUS_CHOICES)
     phone=models.CharField(max_length=10,blank=True,null=True)
     location=models.CharField(max_length=100,blank=True,null=True)
     profile=models.ImageField(upload_to="images/users",blank=True,null=True,default='images/users/default/brand.png')
    

     def __str__(self):
         return f'{self.user}'

accounts/forms.py
from django import forms
from .models import Profile



class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        # fields='__all__'
        exclude=[
            'user'
        ]
        labels={
            'profile':'Change Profile Below'

        }
       
        widgets = {
            "profile": forms.FileInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter Your file...",
                    "style": "border-radius:50px",
                }
            ),
            "phone": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter Your file...",
                    "style": "border-radius:50px",
                }
            ),
            "location": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter Your location...",
                    "style": "border-radius:50px",
                }
            ),
        }
        

    # profile=forms.ImageField(required=False)

accounts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import auth
from django.contrib.auth.models import  User
from .models import Profile
from django.contrib import messages



# Create your views here.
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:       
            auth.login(request,user)
            messages.success(request,'Login successfully!')
            return redirect('home')
        else:
            messages.error(request,'invalid credentials')
            return redirect('login')

    else:
        return render(request,'accounts/login.html')


def register(request):
    if request.method=='POST':
            firstname=request.POST['fname']
            lastname=request.POST['lname']
            gender=request.POST['gender']
            username=request.POST['username']
            email=request.POST['email']
            password=request.POST['password']
            confirm_password=request.POST['cpassword']
            if password==confirm_password:
                if User.objects.filter(username=username).exists():
                    messages.error(request,'Username Already exist ')
                    return redirect('register')       
                else:
                    if User.objects.filter(email=email).exists():
                         messages.error(request,'Email Already exist ')
                         return redirect('register')
                    else:
                            user=User.objects.create_user(first_name=firstname,last_name=lastname,username=username,email=email,password=password)
                            auth.login(request,user)
                            messages.success(request,'login successfully!')
                            if gender=='1':
                                my_status='Mr'                           
                                Profile.objects.create(user_id=request.user.id, profile='images/users/default/he.png',status=my_status)
                                return redirect('default.index')

                            elif gender=='2':
                                my_status='Miss'
                                Profile.objects.create(user_id=request.user.id, profile='images/users/default/she.png',status=my_status)
                                return redirect('default.index')
                            
                            
                     
            else:
                messages.error(request,"Password doesn't match")
                return redirect('register')

                
    else:
        return render(request,'accounts/register.html')






def logout(request):
        auth.logout(request)
        messages.info(request,'Logout successfully!')
        return redirect('login')




def profile(request):
    if request.method=='POST':

        upload=request.FILES['upload']    
        status=request.POST['status']    
        if 'upload' in request.FILES:

                Profile.objects.filter(user_id=request.user.id).delete()
                Profile.objects.create(user_id=request.user.id, profile=upload,status=status)  
                messages.success(request,'Profile Updated successfully!')
                return redirect('profile')

    else:
      
        return render(request,'accounts/profile.html')



def reset(request):
    if request.method=='POST':
        username=request.POST['username']
        if User.objects.filter(username=username).exists():
            username_only=User.objects.get(username=username)
            username_only.set_password('abgoogle')
            username_only.save()
            messages.success(request,'Password Reset Successfully!')
            return redirect('login')
            
        else:
            messages.error(request,"Username doesn't exist !" )
            return redirect('reset')
           
            
                

    else:
        return render(request,'accounts/reset.html')





      

accounts/templates/accounts/layouts/partials/footer.html
<!-- /.content-wrapper -->
<footer class="main-footer">
    <strong>Copyright &copy; 2024 <a href="#">ST JOSEPH UNIVERSITY IN TANZANIA</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      DESIGNED BY <b></b> 
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>

accounts/templates/accounts/layouts/partials/side.html
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/admin" class="brand-link">
      <!-- <img src="dist/img/AdminLTELogo.png" alt="." class="brand-image img-circle elevation-3"
           style="opacity: .8"> -->
      <span class="brand-text font-weight-light">Accomodation</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <!-- <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image"> -->
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ user }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="." class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Admin Dashboard </p>
                </a>
              </li>
              <li class="nav-item">
                <a href="." class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Normal Dashboard </p>
                </a>
              </li>
             
            </ul>
          </li>

          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Users
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Groups
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>


          
         
          <li class="nav-header">Management</li>
          <li class="nav-item">
            <a href="{% url 'room:index' %}" class="nav-link">
              <i class="nav-icon far fa-calendar-alt"></i>
              <p>
                Rooms
                <span class="badge badge-info right">2</span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'hostel:index' %}" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Hostel
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'course:index' %}" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Course
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a  href="{% url 'department:index' %}" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Department
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a  href="{% url 'allocate:index' %}" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Allocate
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

accounts/templates/accounts/layouts/partials/topbar.html
<!-- Header Area Starts -->
{% load static %}
{% load humanize %}

 <!-- Navbar -->
 <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
     
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
     
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>

      <li class="nav-item dropdown user-menu">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <img src="{{ user.profile.profile.url }}" class="user-image img-circle elevation-2" alt=".">
          <span class="d-none d-md-inline"> {{ user }}</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <!-- User image -->
          <li class="user-header bg-primary">
          <img src="{{ user.profile.profile.url }}" class="img-circle elevation-2" alt=".">
    
          <p>
            {{ user }}
            <small>Member since {{ request.user.date_joined|naturaltime }}</small>
          </p>
          </li>
          <!-- Menu Body -->
          <li class="user-body">
          <div class="row">
            <div class="col-6 text-center">
              {% for group in user.groups.all %}
            <a style="text-transform: uppercase;" href="#">{{ group.name }}</a>
            {% endfor %}
            </div> 
            <div class="col-3 text-center">
            <a href="{% url 'reset' %}" class=""  title="change password">
              <i class="text-danger fa fa-key" ></i>
            </a>
            </div>
            <div class="col-3 text-center">
            <a href="#" title="View logs" >logs</a>
            </div>
          </div>
          <!-- /.row -->
          </li>
          <!-- Menu Footer-->
          <li class="user-footer">
          <a href="{% url 'profile' %}" class="btn btn-default btn-flat">Profile</a>
          <a href="{% url 'logout' %}" class="btn btn-default btn-flat float-right">Sign out</a>
          </li>
        </ul>
        </li> 
     
    </ul>
  </nav>
  <!-- /.navbar -->